FadedFeastcraft = FadedFeastcraft or {}

FadedFeastcraft.Config = FadedFeastcraft.Config or {
    MOD_ID = "FadedFeastcraft",
    MOD_NAME = "FFC",
    MOD_LONG_NAME = "Faded's Feastcraft",
    VERSION = "0.1.0",
    NET_MODULE = "FadedFeastcraft",
    RESULT_FIELD_MEAL = "FadedFeastcraft.FFC_SurvivalMeal",
    MAX_MEAL_INGREDIENTS = 8,
    MIN_MEAL_INGREDIENTS = 1,
}

FadedFeastcraft.Config.KNOWN_SOURCE_MODS = {
    CommonSenseReborn = "CSR Ecosystem",
    CommonSenseRebornB42 = "CSR Ecosystem",
    CommonSenseReborn_B42 = "CSR Ecosystem",
    CommonSenseRebornTest = "CSR Ecosystem",
    CommonSenseReborn_Test = "CSR Ecosystem",
    CommonSenseRebornTestB42 = "CSR Ecosystem",
    CommonSenseReborn_Test_B42 = "CSR Ecosystem",
    CommonSenseRebornB42Test = "CSR Ecosystem",
    CommonSenseRebornB42_Test = "CSR Ecosystem",
    CSRTest = "CSR Ecosystem",
    CSR_Test = "CSR Ecosystem",
    CSRTestB42 = "CSR Ecosystem",
    CSR_Test_B42 = "CSR Ecosystem",
    foodAll_v1 = "FFC Expiry Toolkit",
    EGNHInuman = "FFC Beverage Cellar",
    VanillaFoodsExpanded = "FFC Expanded Pantry",
    AbuelitaLinda = "FFC Cocina Pantry",
    AatheomEMVFSM = "FFC Food Visuals",
    MeatDrying = "FFC Preservation Bench",
    CoolerPlus = "FFC Cold Storage Toolkit",
    NutritionMakesSense = "FFC Nutrition Toolkit",
    twistcalories = "FFC Nutrition Toolkit",
    SnackTime89 = "FFC Snack Shelf",
    AR_Merge_Canned_42 = "FFC Can Consolidation",
    PackPantry = "FFC Canning Bench",
    ["consistent-cooking-names"] = "FFC Naming Compatibility",
    MattSimpleAddonsFriuts = "FFC Foraged Fruit",
    FoodExpirationDate = "FFC Expiry Toolkit",
    SkbDriedFood = "FFC Dry Storage",
    TedFoodPack = "FFC Snack Shelf",
    CraftableVanillaFoodItems = "FFC Homestead Recipes",
    MREfood4213 = "FFC Field Rations",
    EliazBetterCanningJarredFoodB42 = "FFC Jarred Pantry",
    TCAllergyTraits = "FFC Trait Safety Toolkit",
    BetterCooking_CN = "FFC Translation Compatibility",
}

FadedFeastcraft.Config.CSR_MOD_IDS = {
    "CommonSenseReborn",
    "CommonSenseRebornB42",
    "CommonSenseReborn_B42",
    "CommonSenseRebornTest",
    "CommonSenseReborn_Test",
    "CommonSenseRebornTestB42",
    "CommonSenseReborn_Test_B42",
    "CommonSenseRebornB42Test",
    "CommonSenseRebornB42_Test",
    "CSRTest",
    "CSR_Test",
    "CSRTestB42",
    "CSR_Test_B42",
}

FadedFeastcraft.Config.SOURCE_PREFIXES = {
    ["FadedFeastcraft."] = "FFC",
    ["MattSimpleAddons."] = "FFC Foraged Fruit",
    ["AdvancedDrying42."] = "FFC Preservation Bench",
    ["CoolerPlus."] = "FFC Cold Storage Toolkit",
    ["SnackTime89."] = "FFC Snack Shelf",
    ["AbuelitaLinda."] = "FFC Cocina Pantry",
    ["VFX."] = "FFC Expanded Pantry",
    ["MR."] = "FFC Field Rations",
    ["Ted."] = "FFC Snack Shelf",
    ["TedFoodPack."] = "FFC Snack Shelf",
    ["DriedFoodMod."] = "FFC Dry Storage",
    ["ExtraCraft."] = "FFC Canning Bench",
    ["archer."] = "FFC Beverage Cellar",
    ["AEMVFSM."] = "FFC Food Visuals",
    ["EliazBetterCanningJarredFoodB42."] = "FFC Jarred Pantry",
    ["Base.CSR_"] = "CSR Ecosystem",
}

return FadedFeastcraft.Config
