local function addProc(bucket, item, weight)
    if not ProceduralDistributions or not ProceduralDistributions.list then return end
    local distribution = ProceduralDistributions.list[bucket]
    if not distribution or not distribution.items then return end
    table.insert(distribution.items, item)
    table.insert(distribution.items, weight)
end

local function addVehicle(bucket, item, weight)
    if not VehicleDistributions then return end
    local distribution = VehicleDistributions[bucket]
    if not distribution or not distribution.items then return end
    table.insert(distribution.items, item)
    table.insert(distribution.items, weight)
end

local function addManualSet(bucket, weightMultiplier)
    weightMultiplier = weightMultiplier or 1
    addProc(bucket, "FAM.FieldTraumaManual", 1.2 * weightMultiplier)
    addProc(bucket, "FAM.EmergencyPharmacologyNotes", 1.0 * weightMultiplier)
    addProc(bucket, "FAM.SanitationFieldManual", 0.8 * weightMultiplier)
    addProc(bucket, "FAM.SurgicalAmputationManual", 0.55 * weightMultiplier)
    addProc(bucket, "FAM.ProstheticFittingGuide", 0.55 * weightMultiplier)
    addProc(bucket, "FAM.VascularAccessGuide", 0.7 * weightMultiplier)
end

local function preDistributionMerge()
    addProc("MedicalClinicDrugs", "FAM.PillsCommercialPainkillers", 9)
    addProc("MedicalClinicDrugs", "FAM.PillsPrescriptionPainkillers", 5)
    addProc("MedicalClinicDrugs", "FAM.PillsCommercialAntibiotic", 4)
    addProc("MedicalClinicDrugs", "FAM.PillsCommercialSedative", 4)
    addProc("MedicalClinicDrugs", "FAM.BottleFluMedication", 5)
    addProc("MedicalClinicDrugs", "FAM.PowderPackFluMedication", 4)
    addProc("MedicalClinicDrugs", "FAM.BottleCoughSyrup", 5)
    addProc("MedicalClinicDrugs", "FAM.NasalSpray", 5)
    addProc("MedicalClinicDrugs", "FAM.BurnTreatment", 3)
    addProc("MedicalClinicDrugs", "FAM.PowderPackHemostatic", 2)
    addProc("MedicalClinicDrugs", "FAM.SealedBandage", 8)
    addProc("MedicalClinicDrugs", "FAM.StumpCareKit", 1.5)
    addProc("MedicalClinicDrugs", "FAM.AntisepticWashKit", 3)
    addProc("MedicalClinicDrugs", "FAM.IVKit", 2)
    addProc("MedicalClinicDrugs", "FAM.SalineBag", 2.5)
    addProc("MedicalClinicDrugs", "FAM.FieldBloodPack", 0.5)
    addProc("MedicalClinicDrugs", "FAM.EpinephrineInjector", 1.5)
    addProc("MedicalClinicDrugs", "FAM.FieldMedicalJournal", 1.2)

    addProc("ArmyStorageMedical", "FAM.SyretteHighGradePainkillers", 2)
    addProc("ArmyStorageMedical", "FAM.SyretteAdrenalin", 2)
    addProc("ArmyStorageMedical", "FAM.SyrettePrescriptionAntibiotic", 2)
    addProc("ArmyStorageMedical", "FAM.SyrettePrescriptionSedatives", 2)
    addProc("ArmyStorageMedical", "FAM.PowderPackHemostatic", 5)
    addProc("ArmyStorageMedical", "FAM.Tourniquet", 7)
    addProc("ArmyStorageMedical", "FAM.SealedBandage", 9)
    addProc("ArmyStorageMedical", "FAM.StumpCareKit", 2)
    addProc("ArmyStorageMedical", "FAM.AntisepticWashKit", 4)
    addProc("ArmyStorageMedical", "FAM.IVKit", 4)
    addProc("ArmyStorageMedical", "FAM.SalineBag", 4)
    addProc("ArmyStorageMedical", "FAM.FieldBloodPack", 1.2)
    addProc("ArmyStorageMedical", "FAM.EpinephrineInjector", 3)
    addProc("ArmyStorageMedical", "FAM.BasicArmProsthesis", 0.4)
    addProc("ArmyStorageMedical", "FAM.HookArmProsthesis", 0.2)

    addProc("BookstoreMedical", "FAM.FieldTraumaManual", 4)
    addProc("BookstoreMedical", "FAM.EmergencyPharmacologyNotes", 3)
    addProc("BookstoreMedical", "FAM.SanitationFieldManual", 2)
    addProc("BookstoreMedical", "FAM.SurgicalAmputationManual", 1)
    addProc("BookstoreMedical", "FAM.ProstheticFittingGuide", 1)
    addProc("BookstoreMedical", "FAM.VascularAccessGuide", 1.5)
    addProc("BookstoreMedical", "FAM.FieldMedicalJournal", 3)
    addProc("LibraryMedical", "FAM.FieldTraumaManual", 3)
    addProc("LibraryMedical", "FAM.EmergencyPharmacologyNotes", 2)
    addProc("LibraryMedical", "FAM.SanitationFieldManual", 2)
    addProc("LibraryMedical", "FAM.SurgicalAmputationManual", 1)
    addProc("LibraryMedical", "FAM.ProstheticFittingGuide", 1)
    addProc("LibraryMedical", "FAM.VascularAccessGuide", 1)
    addProc("LibraryMedical", "FAM.FieldMedicalJournal", 2)
    addProc("UniversityLibraryMedical", "FAM.FieldTraumaManual", 4)
    addProc("UniversityLibraryMedical", "FAM.EmergencyPharmacologyNotes", 4)
    addProc("UniversityLibraryMedical", "FAM.SanitationFieldManual", 3)
    addProc("UniversityLibraryMedical", "FAM.SurgicalAmputationManual", 2)
    addProc("UniversityLibraryMedical", "FAM.ProstheticFittingGuide", 2)
    addProc("UniversityLibraryMedical", "FAM.VascularAccessGuide", 2)
    addProc("UniversityLibraryMedical", "FAM.FieldMedicalJournal", 4)
    addProc("ArmyStorageMedical", "FAM.SurgicalAmputationManual", 0.5)
    addProc("ArmyStorageMedical", "FAM.SanitationFieldManual", 0.8)
    addProc("ArmyStorageMedical", "FAM.ProstheticFittingGuide", 0.5)
    addProc("ArmyStorageMedical", "FAM.VascularAccessGuide", 0.7)
    addManualSet("BookstoreMisc", 0.65)
    addManualSet("LibraryBooks", 0.45)
    addManualSet("UniversityLibraryBooks", 0.65)
    addManualSet("CrateMagazines", 0.22)
    addManualSet("MagazineRackMixed", 0.18)

    addVehicle("GloveBox", "FAM.PillsCommercialPainkillers", 0.6)
    addVehicle("GloveBox", "FAM.BottleCoughSyrup", 0.5)
    addVehicle("SurvivalistGloveBox", "FAM.Tourniquet", 2)
    addVehicle("SurvivalistTruckBed", "FAM.PowderPackHemostatic", 2)
    addVehicle("DoctorGloveBox", "FAM.BurnTreatment", 3)
    addVehicle("DoctorTruckBed", "FAM.SealedBandage", 6)
    addVehicle("DoctorTruckBed", "FAM.AntisepticWashKit", 3)
    addVehicle("DoctorTruckBed", "FAM.IVKit", 2)
    addVehicle("DoctorTruckBed", "FAM.SalineBag", 2)
    addVehicle("AmbulanceGloveBox", "FAM.SyretteAdrenalin", 3)
    addVehicle("AmbulanceTruckBed", "FAM.PowderPackHemostatic", 5)
    addVehicle("AmbulanceTruckBed", "FAM.Tourniquet", 6)
    addVehicle("AmbulanceTruckBed", "FAM.StumpCareKit", 2)
    addVehicle("AmbulanceTruckBed", "FAM.AntisepticWashKit", 4)
    addVehicle("AmbulanceTruckBed", "FAM.IVKit", 5)
    addVehicle("AmbulanceTruckBed", "FAM.SalineBag", 5)
    addVehicle("AmbulanceTruckBed", "FAM.FieldBloodPack", 1.5)
    addVehicle("AmbulanceTruckBed", "FAM.EpinephrineInjector", 4)
    addVehicle("FireGloveBox", "FAM.BurnTreatment", 2)
    addVehicle("FireTruckBed", "FAM.BurnTreatment", 4)
end

Events.OnPreDistributionMerge.Add(preDistributionMerge)
